apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omega
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/timothydodd/project-omega
    newTag: main
